from queue import Queue
from collections import deque
waiting_list = Queue()
print(waiting_list)
waiting_list.put("Ahmed")
waiting_list.put("Ibra")
waiting_list.put("Marcelo")
waiting_list.put("Joe")
print(waiting_list.get())
print(waiting_list.get())
print(waiting_list.get())
print(waiting_list.get())
waiting_list2 = deque()
print(waiting_list2)
waiting_list2.append('Ahmed')
waiting_list2.append("fred")
waiting_list2.append('roland')
waiting_list2.append("Ibrahim")
print(waiting_list2)
